### ISSUE TITLE
minSdk 26

### ISSUE THREAD

**Issue by FabioMatt83** [weliem/blessed-android-coroutines#18]
Hello Weliem, 
first of all, congrats on your SDK. My problem is that I'd like to import it into my app but since I need to support devices with at least Oreo on board (Api Level 24) it looks like I cannot because your SDK's minSdk is 26. Is there a reason for that?  Thanks

**Comment by weliem** [comment]
Thanks! Well, I choose 26 because of the following reasons:

- Because that is the minimum for compiling to Java 8
- Because I could then drop <26 BLE bug workarounds and keep the code clean and simple
- We are at 31 now, so that gives 5 Android versions....

But then again, if you fork and modify the minSdk to 24 it will probably work...

**Comment by FabioMatt83** [comment]
Thanks for your quick clarification!
