### ISSUE TITLE
Get all records at once

### ISSUE THREAD

**Issue by vrrashkov** [weliem/blessed-android-coroutines#5]
Currently the setupGLXnotifications listens and returns all the records one by one, how can I retrieve all the records at once, or find the total records available in the device so i know which is the last one. 

I tried returning the last record like that and then checking while it's observing when the last record appears. But on the device I am using it returns the results descending, so the last record appears as the first one. 
`val command = byteArrayOf(OP_CODE_REPORT_STORED_RECORDS, OPERATOR_LAST_RECORD)`

I also tried with "first record" with Byte = 5 but it doesn't get returned. It returns the "Last record" again.  I guess these are device specific issues because i have encountered similar behaviours on different devices. So I'm not sure what will be the correct way to handle that. 

I would appreciate some pointers to how I can achieve that. How to know when all of the records have been returned so I don't miss any recording.

**Comment by weliem** [comment]
Hi, the operator ALL_RECORDS that I use in the example, should give you all records. But indeed, you get them one by one. There is no way to get them all at once. The maximum package size is 20 bytes so that would never fit anyway.

The operator LAST_RECORD should give you the most recent one. If that doesn't work I think you are facing device specific issues....I can only advice to experiment to see how your device behaves.
